name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1' # Run weekly on Mondays
  workflow_dispatch: # Allow manual triggers

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        run_install: false
    
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 20
        cache: 'pnpm'
    
    - name: Check for dependency updates
      id: dependabot
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    
    - name: Create pull request for dependency updates
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore(deps): update dependencies'
        branch: deps-update
        delete-branch: true
        title: 'chore(deps): update dependencies'
        body: |
          This PR updates dependencies to their latest versions.
          
          - Updated by GitHub Actions automated workflow
        labels: |
          dependencies
          automated pr