name: Publish Library

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8
        run_install: false
      
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Lint
      run: pnpm lint
    
    - name: Test library
      run: pnpm test:lib
    
    - name: Build library
      run: pnpm build:lib
    
    - name: Publish library
      run: pnpm publish:lib
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}